#cross browser and cross plot form done by seleinum
---
version: '3.8'
services: 
   debug-hub: 
     image: selenium/hub:latest
     container_name: selenium-hub 
     ports:
       - "4444:4444"
   chrome-node:
     image: selenium/node_chrome:latest
     container_name: chrome-node
     ports:
        - "5900:5900"
     depends_on:
        - debug-hub
   firefox-node:
      image: selenium/node_firefox:latest
      container_name: firefox-node
      ports: 
         - "5901:5900"
      depends_on:
         - debug-hub
...

   
      








...
