FROM ubuntu:latest

# Install required packages
RUN apt-get update && \
    apt-get install -y git maven openjdk-11-jdk && \
    rm -rf /var/lib/apt/lists/*

# Clone your repository
RUN git clone https://github.com/karpanitava/mavenbuild /mavenbuild

# Set working directory
WORKDIR /mavenbuild

# Example: build with Maven
RUN mvn clean install